---
apiVersion: v1
kind: Service
metadata:
    name: jaeger-collector
    labels:
      app: jaeger
      jaeger-infra: collector-service
spec:
    ports:
    - name: jaeger-collector-http
      port: 14268
      protocol: TCP
      targetPort: 14268
    selector:
      app: jaeger
    type: ClusterIP
